name: deploy-backend
run-name: ${{ github.actor }} is deploying timothypew deploy-backend
on: [push]
jobs:
  build:
    runs-on: self-hosted
    environment: production
    steps:
      - uses: actions/checkout@v3
      # - run: rm -rf ~/timothypew-backend/*
      # - run: mkdir -p ~/timothypew-backend
      # - run: cp -r * ~/timothypew-backend
      # - run: cd ~/timothypew-backend
      - run: yarn install
      - run: echo OPEN_WEATHER_MAPS_KEY=${{ secrets.OPEN_WEATHER_MAPS_KEY }} > .env
      - run: echo MY_FROM_EMAIL=${{ secrets.MY_FROM_EMAIL }} >> .env
      - run: echo MY_TO_EMAIL=${{ secrets.MY_TO_EMAIL }} >> .env
      - run: echo SENDGRID_API_KEY=${{ secrets.SENDGRID_API_KEY }} >> .env
      - run: pm2 reload ecosystem.config.js && pm2 save
      # - run: pm2 startOrReload ecosystem.config.js
