name: deploy-backend
run-name: ${{ github.actor }} is deploying timothypew deploy-backend
on: [push]
jobs:
  build:
    runs-on: self-hosted
    environment: production
    steps:
      - uses: actions/checkout@v3
      - run: mkdir -p ~/timothypew-backend
      - run: cp -r * ~/timothypew-backend
      - run: yarn install
      - run: echo TIMOTHYPEW_BACKEND_PORT=${{ secrets.TIMOTHYPEW_BACKEND_PORT }} >> ~/timothypew-backend/.env
      - run: echo OPEN_WEATHER_MAPS_KEY=${{ secrets.OPEN_WEATHER_MAPS_KEY }} >> ~/timothypew-backend/.env
      - run: pm2 restart "tp-backend"
